### ISSUE TITLE
Overriding styles in Chakra UI 

### ISSUE THREAD

**Issue by devhims** [omgovich/react-colorful#106]
Hi @omgovich, I'm working on a project where your tool has made a world of difference. Sincere thanks!! 
However, when I'm trying to adjust the styles by setting up a separate CSS file, the changes are failing as I'm using Chakra UI which resets CSS by default. Is there any way I can overcome it?

**Comment by omgovich** [comment]
Hi! Which version of react-colorful do you use? v4 and v5 (released a few days ago) are different.

**Comment by devhims** [comment]
I'm on V5.

**Comment by omgovich** [comment]
v5 is an independent CSS-in-JS component:
It appends `<style>` with its styles into the end of `<head>` automatically once the picker is rendered first time. 

It means that most probably your styles (I guess it's a `<link>` tag) are defined before react-colorful's ones.
So you can't override the default react-colorful's styles with a simple "selector" like ".my-react-colorful". 
You need to define a selector with a higher priority like `.my-picker.react-colorful` or `.my-component .react-colorful`.

**Comment by omgovich** [comment]
Give a minute. I'll prepare a demo for you.

**Comment by omgovich** [comment]
Override styles via separate file:
https://codesandbox.io/s/react-colorful-chakra-brdk5

**Comment by devhims** [comment]
Actually, the styles defined before react-colorful are in `style` tags as well. 

<img width="1099" alt="Screenshot 2021-02-16 at 3 02 52 AM" src="https://user-images.githubusercontent.com/17825870/107994906-9d3a7980-7003-11eb-9fec-3f249638d5b7.png">

**Comment by devhims** [comment]
Thanks for the demo. I'm checking it now.

**Comment by omgovich** [comment]
Overriding with `@emotion/styled`:
https://codesandbox.io/s/react-colorful-chakra-emotion-whqul?file=/src/MyPicker.js

**Comment by devhims** [comment]
So much respect for you @omgovich! You saved the day. 🙏

**Comment by omgovich** [comment]
Glad to help! ❤️ Let me know you'll have any other issues.
