### ISSUE TITLE
#NaNNaNNaN as Hex string

### ISSUE THREAD

**Issue by bfsmith** [omgovich/react-colorful#108]
I'm getting back `#NaNNaNNaN` in `onChange` when I start with `color=''` and move the bottom slider without changing the value of the top box. Below is a simple component that demonstrates the issue.

```js
import React, { useState } from 'react';
import { HexColorPicker } from 'react-colorful';

const ColorPicker = () => {
  const [color, setColor] = useState('');
  return (
    <>
      <HexColorPicker color={color} onChange={setColor} />
      {color}
    </>
  );
};

export default ColorPicker;
```

**Comment by omgovich** [comment]
It's always better to set some default color value just because the picker needs to have a pointer placed somewhere.
The picker falls back to the back color if no value (undefined) passed:

```diff
- const [color, setColor] = useState('');
+ const [color, setColor] = useState();
```

**Comment by omgovich** [comment]
Demo: https://codesandbox.io/s/react-colorful-no-value-dvqrm?file=/src/App.js

**Comment by bfsmith** [comment]
In my case, I want the color to be optional. I can modify my UI to allow the user to pick to set a color or not. Thanks for the quick reply and for sharing your work. I love the simplicity of the component's API. 👍
