### ISSUE TITLE
Feature: Better support SSR

### ISSUE THREAD

**Issue by rschristian** [omgovich/react-colorful#109]
I'm writing this PR right now, just thought I'd explain it a bit more in depth first in an issue. I find that helps separate comments about the feature from comments about the specific implementation.

![temp](https://user-images.githubusercontent.com/33403762/108557303-ff260800-72bd-11eb-8c9f-8f5dfe57fede.png)

This comment left on your most recent post got me thinking about SSR, and a way we can improve it.

Firstly, we can provide a hook to the user to allow them to access the CSS string themselves. They can just inject it in the head of their doc if using SSR, for example. While this would be duplicated on load, that wouldn't be an issue.

But, to get around that, we could add an ID to the style element. So `useStyleSheet()` looks for a `<style id="__react-colorful">`, and only if it doesn't find one does it inject a new tag into the head. This way you not only support SSR, but make sure it's efficiently supported at the same time.

Should be quite slick and cover the use cases.

**Comment by omgovich** [comment]
I close the issue if you don't mind. Let's continue the conversation in the PR.
