### ISSUE TITLE
This is not an issue - Is a thank you 😊

### ISSUE THREAD

**Issue by danestves** [omgovich/react-colorful#114]
I'm using this package inside as a [plugin](https://github.com/danestves/strapi-plugin-colorpicker) for Strapi and was really faster the change i need to build a custom component to change from hexadecimal to rgba but is really clean and also using `tinycolor2`, really really thank you for this

**Comment by omgovich** [comment]
I'm glad that you liked react-colorful ❤️
Good luck with your project!
