### ISSUE TITLE
Unable to start the development server (Parcel issue)

### ISSUE THREAD

**Issue by molefrog** [omgovich/react-colorful#117]
I get a Parcel error when trying to run the development server in a newly cloned repo. It's related to the recent regression in Parcel https://github.com/parcel-bundler/parcel/issues/5943

The proposed solution so far is to freeze the Parcel version to `1.12.3` via either Yarn resolutions or `npm-force-resolutions` for NPM users (see https://github.com/parcel-bundler/parcel/issues/5943#issuecomment-789613052).

We could probably solve this by changing the Parcel version req from `^1.12.4` to `1.12.3` or by pushing a package-lock.json.

**Comment by omgovich** [comment]
Fixed, thanks!
