### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by philmetzger** [omgovich/react-colorful#125]
I get the following issue when trying to use react-colorful in my NextJS app:

```
SyntaxError: Cannot use import statement outside a module
 module.exports = require("react-colorful");
```

```
import { HexColorPicker } from "react-colorful";
<HexColorPicker color={color} onChange={setColor} />
```

Anyone know why?

**Comment by omgovich** [comment]
Hi! Thanks for the report!

This package is dual (we publish both ESM and CJS files) so everything should work well everywhere, but probably we can extend package's export somehow to provide better support of Next's SSR.

I'll take a look tomorrow.

**Comment by philmetzger** [comment]
As my solution right now, I use nextJs/dynamic like this:
```
const ColorPickerFormField = dynamic(() => import('src/components/forms/ColorPickerFormField'), { ssr: false });
```

**Comment by omgovich** [comment]
Hi! Still digging into the issue.
Could you tell me which version of Next.js you use?

**Comment by philmetzger** [comment]
I am using next@10.1.3

**Comment by omgovich** [comment]
Just tested it with next@10.1.3. Works well on my machine:

![image](https://user-images.githubusercontent.com/206567/115538777-e7123b00-a2a4-11eb-832d-b84c6d7e0127.png)

![image](https://user-images.githubusercontent.com/206567/115538833-f5f8ed80-a2a4-11eb-8c6c-8083eb7c4d23.png)

I used one of the Next's starters:
```
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"
cd nextjs-blog
npm install react-colorful
npm run dev
```

So it should work with the default Next settings.
Do you have any specific configurations made in next.config.js maybe?

**Comment by philmetzger** [comment]
Hmm not so familiar with the settings, but this is what I have:

```
module.exports = {
    distDir: '../.next',
    webpack: config => {
        const env = Object.keys(process.env).reduce((acc, curr) => {
            acc[`process.env.${curr}`] = JSON.stringify(process.env[curr]);
            return acc;
        }, {});

        config.resolve.modules.push(path.resolve('./'));
        config.plugins.push(new webpack.DefinePlugin(env));

        return config;
    },
    images: {
        domains: ['firebasestorage.googleapis.com'],
    },
};
```

**Comment by rschristian** [comment]
@omgovich I think this is due to the rough ESM support in Node. I think we need to make [the `import` key](https://github.com/omgovich/react-colorful/blob/master/package.json#L15) have a `.mjs` extension. This module's "type" is technically CJS (as `"type": "module"` has not been set) so `.module.js` is treated as CJS in Node. [Example from Preact repo](https://github.com/preactjs/preact/blob/ec88035b34ad5d7843c329bcf14bbdaa77c52cf3/package.json#L14-L17)

 It'd make sense that Next has issues here.

**Comment by omgovich** [comment]
Thanks for your research @rschristian. Sounds like that!

**Comment by deadcoder0904** [comment]
I haven't taken a look at @rschristian's solution but this is a good write-up on how to make ESM packages → https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by rschristian** [comment]
> I haven't taken a look at @rschristian's solution but this is a good write-up on how to make ESM packages → https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

That's about writing pure ESM packages which is definitely not what we want to be doing here and is quite inapplicable.

**Comment by omgovich** [comment]
@philmetzger BTW. What's your Node version? I'm still trying to figure out the reason why the package doesn't work for you, but runs on my machine.

```
node -v
```

**Comment by omgovich** [comment]
Just released `5.1.3`. Not sure that it helps to solve your issue, but it might.
@philmetzger Can you please try to install that?

**Comment by philmetzger** [comment]
I use `v12.20.2`. I just tried `v12.16` and that works fine actually!

Also just tried upgrading to 5.1.3 and its the same as above (works on node 12.16)

**Comment by omgovich** [comment]
Super weird. Might it be a bug of `v12.20.2`? 🤔
I would recommend you to update your env to v14 since it an active LTS version:
![image](https://user-images.githubusercontent.com/206567/115894167-a1e73800-a461-11eb-94c2-801c40928ae5.png)

**Comment by rschristian** [comment]
@omgovich I guess the only thing else I can see is that `"default"` key which points to some ESM. Any reason for needing that? Maybe Node `v12.20.2` is being weird and skipping to that? 

Just guesses at this point, I've not heard of any issues like that.

**Comment by omgovich** [comment]
"default" shouldn't make the things worse. It'a fallback.
Check this thread out:
https://twitter.com/nsfounder/status/1378879896135426051?s=19

"exports" is a complete hell...

**Comment by rschristian** [comment]
I totally agree, it shouldn't, but when it comes to build tools, the module resolution is completely up to them. They can choose to only use certain keys if they'd like. Node on the other hand has that resolution logic built in. It'd be weird for this to work on a different Node version.

**Comment by omgovich** [comment]
It feels that we did everything we could.
Should we close the issue, what do you think guys?

**Comment by omgovich** [comment]
BTW: @philmetzger We forgot to publish the mjs file in v5.1.3.
So v5.1.4 might work for you.

**Comment by philmetzger** [comment]
Havent had time to test it, but i would say we can close this issue.
