### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-colorful' in '/vercel/path0/...'

### ISSUE THREAD

**Issue by e-zhang09** [omgovich/react-colorful#128]
`package.json` has an exports field that includes: `"import": "./dist/index.mjs"` However, the .mjs extension is not specified in the `files` field in `package.json`:

`
"files": [
    "dist/*.{js,ts,map}",
    ...
  ],
`

...which causes the .mjs file to not be included in npm dist. This causes a Webpack ModuleNotFoundError on Linux builds when using ES6 import like `import { HexColorPicker } from 'react-colorful'` (although Window builds still work for some reason).

**Comment by rschristian** [comment]
Whoops, thanks for pointing that out. 

Webpack shouldn't be using that anyways though, as far as I know. Should prioritize the `"browser"` key.

**Comment by e-zhang09** [comment]
Hm, it was probably because I was using SSR with NextJS then. I ended up just forcing webpack to use the normal .js version with:
`const HexColorPicker = require('react-colorful').HexColorPicker`
but I'm sure the .mjs will work fine!

**Comment by omgovich** [comment]
Hi! Released `v5.1.4` with the fix included.
