### ISSUE TITLE
Include basic color conversion algorithms

### ISSUE THREAD

**Issue by DanishShah** [omgovich/react-colorful#130]
I think we need some basic color conversion algorithm to ensure better performance. Right now using a third-party library like `tinycolor2` causes app freeze.

Usecase:
I want to allow the user to either choose a `hex` color or `rgba` color. We are storing `hex` code at the backend so whenever the user chooses a `rgba` color we need to convert that to a `hex8` string. but since the `RgbaColorPicker` accepts `RgbColor` type we need to convert the color to that everytime the color changes. When you constantly do this in `RgbaColorPicker` it crashes the app.

Ways to reproduce:
Open the code sandbox link: https://codesandbox.io/s/react-colorful-wlm00
Try changing the color continuously and quickly, it will work fine in case of rgb.
Now move the alpha slider and try the same again, after some time it freezes.

**Comment by rschristian** [comment]
This is where you should be using a debounce hook. You definitely don't want to be running that conversion, or any conversion for that matter, every time the value changes. Even simple conversion will be super expensive with normal movement in a color picker.

I don't think this is really an issue with the library, but more your setup.

**Comment by omgovich** [comment]
Hi! Don't run the conversion on every tick and skip it if the value is already in the valid color space.
We have an example in our README that illustrates a proper approach:
https://codesandbox.io/s/6fp23?file=/src/CustomPicker.js

**Comment by omgovich** [comment]
We're not planning to add all of the color conversion methods to the color picker itself since it increases the picker size ~3x times. **react-colorful** is a micro-library and it aims to be as small as possible.

BTW: If you looking for a better converter, check our new library out. It's 3 times faster than tinycolor2.
https://github.com/omgovich/colord

**Comment by DanishShah** [comment]
Thanks for the quick reply
