### ISSUE TITLE
How to check if handleChange is complete?

### ISSUE THREAD

**Issue by 19992077** [omgovich/react-colorful#134]
How can I check if handleChange has completed? I get that it uses hooks so it updates in real-time, but is there a way to check if the handleChange has completed?

My goal is to get check if once the user has choosen his colour, I'm executing another function.

I'm using this package with Three.js within a React.js app to change the color of the background scene. 

Here is some code I'm using including what I tried:

```js
const MyComponent = (background) => {
  const [currBackground, setCurrBackground] = useState(background)  
  const threeCanvas = useRef()

  useEffect(() => {
    // some three.js code
  }, [])

  const handleBackgroundChange = useCallback((value) => {
    setCurrBackground(value)
    scene.background = new THREE.Color(value)
    // other three.js code
  }, [scene])

  return (
    <>
      <div ref={threeCanvas} />
      <HexColorPicker
        color={currBackground}
        onChange={handleBackgroundChange}
       />
    </>
  )
}
```

Many thanks in advance, this package is amazing.

**Comment by omgovich** [comment]
Hi! Check "Code Recipes" section in the README:
https://github.com/omgovich/react-colorful#code-recipes

I guess "Values denouncing" is the thing you are looking for.

**Comment by 19992077** [comment]
> 
> 
> Hi! Check "Code Recipes" section in the README:
> https://github.com/omgovich/react-colorful#code-recipes
> 
> I guess "Values debouncing" is the thing you are looking for.

Thank you this example worked!
