### ISSUE TITLE
[Error] Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by ajaypillay** [omgovich/react-colorful#136]
Hi, my browser's console keeps throwing this error, when all I have done is embedded `<HexColorPicker color={color} onChange={setColor} />` in a functional component.

I tried setting `touch-action: none` to all parent divs up to `body` but the error is still being thrown. That being said, the color picker works fine on desktop and mobile, it's just that I'm not sure why this error is being thrown.

Any suggestions on remedying this?

This is a great library by the way! I avoided starting off with `react-color` because it seems outdated and has many open issues, while this is far more recent and modernized. Thank you for this.

**Comment by omgovich** [comment]
Hi! I guess the problem is in your `setColor` function.

I assume it looks like this:
```js
const setColor = (e) => {
  e.preventDefault()
  console.log(e.target.value)
}
```
But react-colorful doesn't; return event object in the event handler. So it has to be:
```js
const setColor = (value) => {
  console.log(value)
}
```

**Comment by ajaypillay** [comment]
Unfortunately my code is exactly as per the Readme.
```
import { HexColorPicker } from "react-colorful";
const Component = () => {
  const [color, setColor] = useState("#aabbcc");
  return <HexColorPicker color={color} onChange={setColor} />;
};
```
I've tested it on a blank page with no other components or touch events going on, and I can't seem to figure out why this is happening.

**Comment by omgovich** [comment]
Could you please provide an error stack trace? Just screenshot dev tools console for example.

**Comment by omgovich** [comment]
Not sure that error is inside of react-colorful since we don't use passive event listeners 🤔

**Comment by ajaypillay** [comment]
![image](https://user-images.githubusercontent.com/917752/120114388-964e0600-c1b1-11eb-85c4-d2411bcbedda.png)
I'm trying to debug this a little further. I'm running Meteor, and I think something is conflicting with this.
![image](https://user-images.githubusercontent.com/917752/120114449-d0b7a300-c1b1-11eb-9718-816ee3c6c24b.png)

**Comment by omgovich** [comment]
I'll try to create a Meteor app and run react-colorful there. Let you once I have some results.

**Comment by ajaypillay** [comment]
Thank you very much for the help.

**Comment by omgovich** [comment]
Hi! What version of react-dom do you use in your project?
Seems like it's relevant to this issue https://github.com/facebook/react/pull/19654 and having 17.0.1+ should help.

**Comment by ajaypillay** [comment]
My `react-dom` version is 17.0.2, which is the latest version right now.

**Comment by omgovich** [comment]
Got it. Seems like the source of the problem is that `touchstart` event is now passive by default in the browsers.
Will try to find a workaround.

**Comment by ajaypillay** [comment]
> Got it. Seems like the source of the problem is that `touchstart` event is now passive by default in the browsers.
> Will try to find a workaround.

Interesting, thank you for the fix! Sincerely appreciated.

**Comment by omgovich** [comment]
Please try the new v5.2.2 and let me know the warning is still present.

**Comment by ajaypillay** [comment]
Just tested it and the warning isn't being thrown anymore, and it still works perfectly fine.

**Comment by omgovich** [comment]
Nice! Thanks for pointing out the bug and best of luck with your project)
