### ISSUE TITLE
Hue slider vertical orientation

### ISSUE THREAD

**Issue by mikeyaworski** [omgovich/react-colorful#138]
For a `HexColorPicker`, is there a way to put the hue slider on the right or left of the saturation, as opposed to above/below?

This is the default behavior with it below: 

![image](https://user-images.githubusercontent.com/10966214/120128637-7e19bf00-c190-11eb-8c83-978792c2bfdd.png)

Is it possible to make style changes to orient the slider vertically, or would that inevitably fail due to how the slider logic works?

**Comment by omgovich** [comment]
Hi! The vertical orientation is not supported at the moment, and we do not have it in plans. React-colorful is a micro-library and we prefer to ship the most important and popular functionality in the minimum amount of bytes. The vertical bar seems a pretty rare case and we don't want to make the component heavier.
