### ISSUE TITLE
Top left border artifact

### ISSUE THREAD

**Issue by nikolaik** [omgovich/react-colorful#139]
Hi there, I've noticed there's an artifact at the top left border of the picker.

![Screenshot from 2021-05-31 11-41-16](https://user-images.githubusercontent.com/104154/120174978-fe2e3c00-c205-11eb-97f9-41915810c3e2.png)

Picking a contrasting color with the backgrond makes it easier to see. If I remove the following style the artifact goes away, but other elements shift a bit.

https://github.com/omgovich/react-colorful/blob/0e52d102eb757145365fe8844f1d2b95c535d01e/src/css/styles.css#L14

Do you see a better way of fixing the artifact?

Really like this component 💖

**Comment by omgovich** [comment]
Hi! Also don't like that border-radius artifact.
Didn't know that border-bottom affects that! Feels like it might help to finally fix the bug! I'll do some experiments and come back to you soon.

**Comment by nikolaik** [comment]
> I'll do some experiments and come back to you soon.

Nice, looking forward too it!

**Comment by omgovich** [comment]
Fixed in v5.2.1. Thanks!

**Comment by nikolaik** [comment]
> Fixed in v5.2.1. Thanks!

So fast, thank you!
