### ISSUE TITLE
sidebar

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [omgovich/react-colorful#144]
Hello, is it possible to have the "react-colorful__hue" bar on the side of the color selector ? I tried this but as you see it's not working very well.
![image](https://user-images.githubusercontent.com/79476242/124197179-445d1080-dace-11eb-8af8-2ed112fe74f0.png)

**Comment by omgovich** [comment]
Hi! The vertical orientation is not supported at the moment, and we do not have it in plans.

React-colorful is a micro-library: we prefer to ship the most important and popular functionality in the minimum amount of bytes. The vertical bar seems a pretty rare case and it doesn't seem fair to make the component heavier for everyone by adding support of it.

Can I ask you why do you prefer vertical bars over horizontal ones?

**Comment by Alexandre-Fernandez** [comment]
I was experimenting with UI and in some cases the having the extra width instead of the extra height can help that's all, but as you say it's not that important.
Thanks for your work and fast reply!
