### ISSUE TITLE
Include "#" in HexColorInput

### ISSUE THREAD

**Issue by grelas** [omgovich/react-colorful#145]
Is there a particular reason that we're [removing](https://github.com/omgovich/react-colorful/blob/master/src/components/HexColorInput.tsx#L7) `#` from the `HexColorInput` component on change? `react-colorful` is perfect for my needs, but there's no ability to customize this display behavior. The only workaround I can think of is UI hackery to render a "#" next to the input.

**Comment by omgovich** [comment]
Hi @grelas! I have received a few complaints about that already, so I guess it's time to implement a way to enable `#`. I'll take a look soon and let you know about the results!

**Comment by omgovich** [comment]
Hi! Check `v5.3.0` with the new `prefixed` prop included:

```jsx
<HexColorInput color={color} onChange={setColor} prefixed />
```
