### ISSUE TITLE
Empty Widget with 0 width

### ISSUE THREAD

**Issue by ManuelKraemer** [omgovich/react-colorful#147]
Hey there.
First of all: Thank you for this great widget. It's super easy to use! 
I just created a new react component with the HexColorPicker (v.4.4.4) but it doesn't show up:
```javscript
import { useState } from "react";
import { HexColorPicker, HexColorInput } from "react-colorful";

export default function Design(props) {
    const [color, setColor] = useState("#aabbcc");
    return (
        <div className="designContainer">
            <h1>Design</h1>
            <div className="flex justify-around">
                Color:
                <HexColorPicker color={color} onChange={setColor} />
                <HexColorInput color={color} onChange={setColor} />
            </div>
        </div>
    );
}
```

In the Chrome dev tools I can see that the widget has 0 width
![image](https://user-images.githubusercontent.com/34281800/125792845-83bc7164-2c4d-4ed6-8790-bc9624cca47e.png)
Can anyone help me with this? Did I miss something?
Regards,
Manuel

**Comment by omgovich** [comment]
Hi! If use are using v4 you need to import CSS file as well. But I eould recommend you to migrate to v5 which doesnt require any CSS imports

**Comment by ManuelKraemer** [comment]
Wow that was an easy fix! Thank you!
