### ISSUE TITLE
custom properties in preset colors

### ISSUE THREAD

**Issue by dmartinjs** [omgovich/react-colorful#149]
# Description
Currently, custom properties are rendered as black in the preset colors.

Example:
```javascript
const presetColors = ["var(--primary)"];
```
<img width="200" alt="Capture d’écran 2021-07-21 à 17 38 22" src="https://user-images.githubusercontent.com/53537199/126517609-76e43b13-cd03-460c-85b3-4628d5775ea6.png">

# Expected behavior
handle custom properties and display the color of the custom properties in the preset colors.

<img width="200" alt="Capture d’écran 2021-07-21 à 17 38 22" src="https://user-images.githubusercontent.com/53537199/126518428-1cc018eb-106c-4ca5-95dd-6ffef19bc32c.png">

**Comment by omgovich** [comment]
Hi! Thanks for using `react-colorful`.
Where did you find the UI with presets? `react-colorful` doesn't have this feature included.

**Comment by omgovich** [comment]
It looks like Storybook UI. The presets are implemented there, it's not a part of `react-colorful` package.

**Comment by dmartinjs** [comment]
Yes, it's from Storybook. 
I though it was part of the lib when I saw documentation about preset in the readme of the project.

sorry for my mistake.
