### ISSUE TITLE
Support for transparency in HexColorInput

### ISSUE THREAD

**Issue by Kilian** [omgovich/react-colorful#154]
The HexColorInput doesn't seem to support the [#rrggbbaa or #rgba color notation](https://caniuse.com/css-rrggbbaa) (hex colors with an extra digit/digit pair for transparency), as it limits the length to 6 digits. It would be nice if it also supported the 8-digit notation that includes transparency!

It could be as easy as changing the `substring` here to go from `0,6` to `0,8`: https://github.com/omgovich/react-colorful/blob/master/src/components/HexColorInput.tsx#L7

**Comment by omgovich** [comment]
Hi 👋 Agree! I guess we also need to implement `Hex8ColorPicker`.

**Comment by omgovich** [comment]
Hi! Just released v5.4.0. Now `HexColorInput` support additional `alpha` property to enable `#rgba` and `#rrggbbaa` formats.

**Comment by Kilian** [comment]
Awesome, thanks!
