### ISSUE TITLE
Is it possible to only have a 2D color chooser?

### ISSUE THREAD

**Issue by MarcusHSmith** [omgovich/react-colorful#173]
<img width="218" alt="Screen Shot 2022-02-04 at 3 15 26 PM" src="https://user-images.githubusercontent.com/5768890/152604091-4b37b396-fcf3-43dc-9be3-b3513be10ebb.png">

Is it possible to remove the 3D chooser and only show the 2D slider?

**Comment by omgovich** [comment]
Hi! Could you please clarify what "3D chooser" means?
