### ISSUE TITLE
How can I use a hue picker vertically?

### ISSUE THREAD

**Issue by mustaquenadim** [omgovich/react-colorful#178]
I'm facing an issue customizing react-colorful. I want to design a color-picker like the image attached below.

![Design](https://user-images.githubusercontent.com/56265819/161478644-f44c0591-487e-4547-95fa-4caddf2b1d97.png)

I've written custom CSS to give looks like this. But hue slider doesn't work vertically. It only works horizontally. Please help!

**Comment by omgovich** [comment]
Hi! The vertical orientation is not supported at the moment, and we do not have it in plans. React-colorful is a micro-library: we prefer to ship the most important and popular functionality in the minimum amount of bytes. The vertical bar seems a pretty rare case and it doesn't seem fair to make the component heavier for everyone by adding support of it.
