### ISSUE TITLE
Usage with classes?

### ISSUE THREAD

**Issue by matronator** [omgovich/react-colorful#185]
Hi, is it possible to use this with classes? When I put this into a class with `onChange={this.changeColor}` the whole page turns completely white as soon as I click on any color and some errors pop-up in the console.

**Comment by omgovich** [comment]
Hi! I'm pretty sure that the component works inside class components. Please share your `changeColor` code.

**Comment by matronator** [comment]
Nevermind, I got it working. I don't know why, but adding the onChange as a reference to a class function (like in the original comment `onChange={this.onChange}`) just kept crashing. I finally got it to work when I inlined the entire function, so it looks like this:

```tsx
<PopoverPicker
  color={this.state.preview.border.color}
  selectValue={this.state.preview.border.style}
  onChange={(color: string) => this.setState({ preview: { ...this.state.preview, color: color }})}
/>
```

Can't figure out why it only seems to work when it's inlined like this, though.
