### ISSUE TITLE
Request for React 18 Compatibility

### ISSUE THREAD

**Issue by queee03** [omgovich/react-colorful#210]
I would like to request official support for React 18 in the project. Currently, the project only supports up to React 17. It would be greatly appreciated if the project could provide compatibility with React 18.
Thank you for considering this request.

**Comment by owaisahmed5300** [comment]
I was thinking to try out this library but I'm not sure if it is supported/compatible with react 18 or in development? Anybody can confirm..?

**Comment by satelllte** [comment]
Not sure about the official state of the library's React 18 support, but I've used it recently in Next.js 14 app with React 18 and  no issues faced so far. At least for `RgbColorPicker` component.

Here's the use case reference:
[satelllte/displacementx](https://github.com/satelllte/displacementx) | [src/components/pages/Generator/CanvasSection/Gradient/ColorPicker/ColorPicker.tsx](https://github.com/satelllte/displacementx/blob/main/src/components/pages/Generator/CanvasSection/Gradient/ColorPicker/ColorPicker.tsx)

**Comment by owaisahmed5300** [comment]
I tested on react 18 and worked very well. No issues!
