### ISSUE TITLE
Should the package distribution contain minified sources?

### ISSUE THREAD

**Issue by molefrog** [omgovich/react-colorful#27]
I was surprised to see that the unpacked size of the package is **443 kB**. Turns out it has minified sources with source maps, that weight ~16kb each:

```
├── [ 79K]  dist
│   ├── [1015]  index.css
│   ├── [3.2K]  index.esmodule.js
│   ├── [ 16K]  index.esmodule.js.map
│   ├── [3.6K]  index.js
│   ├── [ 16K]  index.js.map
│   ├── [3.5K]  index.module.js
│   ├── [ 16K]  index.module.js.map
│   ├── [3.8K]  index.umd.js
│   └── [ 16K]  index.umd.js.map
```

I wonder if the distribution should contain minified sources at all. Thoughts?

**Comment by omgovich** [comment]
Hmmm. I guess we could remove them from the bundle to make package installation faster.
It's easy to do with microbundle (just need to add `--sourcemap false` to CLI command).

**Comment by molefrog** [comment]
@omgovich Right, should we also turn the minification off? It's a small detail, but could result in better DX: I often read sources straight from the `node_modules` folder.

**Comment by omgovich** [comment]
I would keep the minification enabled because I like to control the bundle size. 
Microbundle/rollup converts my code a lot during the minification and I keep this rules in mind during the features development.
Some another bundler could do it another way.

**Comment by omgovich** [comment]
Going to update the bundler settings as soon as TS migration is done.
