### ISSUE TITLE
Too many type definition files

### ISSUE THREAD

**Issue by omgovich** [omgovich/react-colorful#31]
Since we migrated the entire codebase to TS, each dist folder contains a lot of `.d.ts` files.

The total number of them is more than 100.

In my opinion, it would be great to find some way to have one primary type definition file in each folder.

**Comment by omgovich** [comment]
@RyanChristian4427 Could you join me here?

**Comment by RyanChristian4427** [comment]
I don't disagree, it is a bit messy, but currently Microbundle offers no types bundling functionality. [Link to closed issue requesting this](https://github.com/developit/microbundle/issues/644).

Right now we'd need to find another tool to bundle them together, and this might be difficult given the project structure. Dumb bundling is certainly easy enough, but I have no idea if an intelligent bundler exists, where it will follow the tree using a package's `types` field to see what should and shouldn't be included.

**Comment by omgovich** [comment]
Let's skip then for now. It doesn't affect the library itself — the only thing I don't like is NPM's `Total Files` field (which is `163` now).
