### ISSUE TITLE
Internet explorer support

### ISSUE THREAD

**Issue by pokorson** [omgovich/react-colorful#37]
Currently examples are not working on internet explorer 11.
Are there any plans for supporting it?

**Comment by omgovich** [comment]
Hi, @pokorson. Thanks for your report
This is probably not the library's issue, but Parcel's (which we use to build the demo) one. I will dig into Parcel options.

**Comment by byr-gdp** [comment]
Maybe u could have a try to set the "browser" key in package.json https://github.com/parcel-bundler/parcel/issues/230#issuecomment-372967707

**Comment by omgovich** [comment]
Seems that it should help, it doesn't.
Probably because of the current library's building scripts.

@RyanChristian4427 and I are working on [the modernization and simplification of the project packaging](https://github.com/omgovich/react-colorful/pull/42) and when it will be done, we will try to apply `browserslist` again.

**Comment by omgovich** [comment]
Hey @pokorson. The component itself works almost everywhere. Tested even in browsers that were released before 2015 (Chrome 40, Firefox 32, Opera 25, Safari 9, and Edge 12). Everything works as expected.

To make our pickers work in IE11 you should add `Object.assign` polyfill to your code.
We just released `v4.1.1` with better IE11 support and updated the README to mention that you need the polyfill to fix IE11 support.

I added the polyfill to our demo page and it now works in IE11:
<img width="1525" alt="Xnip2020-09-25_23-41-06" src="https://user-images.githubusercontent.com/206567/94332215-c0747600-ffdb-11ea-9662-2b7941cbd286.png">

**Comment by pokorson** [comment]
@omgovich thanks!
