### ISSUE TITLE
Discussion: Alpha channel picker design

### ISSUE THREAD

**Issue by omgovich** [omgovich/react-colorful#46]
Since we're going to add RGBA and HSLA color models support, we need to decide how the picker (for these color models) will look like.

![image](https://user-images.githubusercontent.com/206567/92704373-95dbb980-f35b-11ea-93f7-2717641a6e2d.png)

Which option do you like most, guys?
@molefrog @RyanChristian4427 @jeetiss

**Comment by omgovich** [comment]
I like **1** and **2**.

The first one looks modern and I assume it's better in terms of UX — harder to click on `Hue` accidentally when trying to change an alpha value and vice versa.

The second one is also good because it keeps the UI as a single component — easier to add the picker to dropdowns (without adding an extra background/wrapper), etc.

**Comment by molefrog** [comment]
Definitely 2nd IMO. I like how it looks like an extension of the standard ColorPicker component. It would be also nice if you could import an alpha channel slider separately.

**Comment by RyanChristian4427** [comment]
I'd vote for #2 too. Same reason, looks like more of an extension and keeps it tightly knit.

**Comment by omgovich** [comment]
Will start implementing the second design then. Thanks guys!

**Comment by RyanChristian4427** [comment]
@omgovich I mentioned it before a while back but it looks like [this fork started to implement alpha](https://github.com/xpl/react-colorful) to some degree. Haven't looked through the actual code myself but it's possible that they did it quite well. Might be worth taking a glance to see if it can be merged in some way.

**Comment by omgovich** [comment]
Hey @molefrog @RyanChristian4427 

After a few experiments, I started to seem that 3️⃣ is the best in terms of UX.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/206567/93074298-d05f9200-f68c-11ea-92a6-3376ac550f79.gif)

When we display 3 pointers it's easier to understand that the top one is the primary one to choose a color.
Also, it seems strange to me to have a big handle to adjust alpha.

3️⃣ looks more traditional and familiar, so it should be easier to use. What do you think?

**Comment by omgovich** [comment]
Forget about that. Decided to keep circles)
