### ISSUE TITLE
Fast Tap and Release on Alpha or Hue Slider Causes Incorrect Selection

### ISSUE THREAD

**Issue by femetrie** [omgovich/react-colorful#55]
Noticed a small issue on iOS (13.7, tested on iPad and iPhone) that feels like a debounced input issue. To reproduce, start a tap and drag **away from the scrubber** and then release quickly. You’ll see the color revert to the initial tap, not the final drag. [Here’s a video of how it looks](https://i.imgur.com/gNlVJx7.gifv).

Also, I’m a big fan of this library. Surprising how few options there are out there and none of them at a reasonable size.

**Comment by omgovich** [comment]
Thanks for your feedback. Will dig into that as soon as I can.

**Comment by omgovich** [comment]
@femetrie bug is fixed. Could you please check [the demo](https://omgovich.github.io/react-colorful/) on the real iPhone? I don't have one and tested using the BrowserStack)
