### ISSUE TITLE
Suggestion: names for components viewed in dev tools

### ISSUE THREAD

**Issue by atomcorp** [omgovich/react-colorful#61]
Hello again :)

Just a small suggestion, it would be nice to see the names of the components when viewing them in dev tools. Currently they use minified output.

![image](https://user-images.githubusercontent.com/3504434/93871320-5d769c80-fcc6-11ea-9252-95f2f6ee7ff9.png)

Thanks!

**Comment by omgovich** [comment]
Hi @atomcorp!

The primary goal of this library is to be supersmall in terms of bundle size and I don't see any way to provide `displayName` for every component without affecting the library size dramatically. So I think, we won't do that.

**Comment by omgovich** [comment]
In case an error throws from the component we provide source maps with the package.
To customize the component, you could check the docs or/and standard DevTools.

**Comment by atomcorp** [comment]
No problem. I'm suprised DevTools doesn't implement sourcemaps in some way, seems a shame.
