### ISSUE TITLE
CSS-in-JS version?

### ISSUE THREAD

**Issue by omgovich** [omgovich/react-colorful#72]
Hey guys! @molefrog @rschristian @jeetiss 

A lot of projects use CSS-in-JS and don't have any CSS-loader configured.
That makes react-colorful adding way harder for them.

Seems to me that it's hard to compete with react-color (that uses emotion) while our installation requires additional actions.

So I thought what if we find some way to avoid CSS-loading and will inject styles to a webpage?

Still don't know how to do it better. Thoughts?

**Comment by omgovich** [comment]
Don't think that usage of emotion or styled-components is our way since they cost more than 10 KB.
We could probably use something like `goober` (1KB): https://github.com/cristianbote/goober

But we don't actually need CSS-in-JS itself. We just need a way to inject our styles into a webpage.

**Comment by rschristian** [comment]
Alternatively, read in the stylesheet and inject it into the styles portion of the document. I've done that before, works well enough.

**Comment by rschristian** [comment]
Far less than 1kb but rather "dumb". In certain contexts (especially in dev) you'll get a build up of these style elements in the document. Should be pretty harmless and will disappear with a refresh though.

**Comment by omgovich** [comment]
I don't how to write styles if we are going go with this approach. Should we write them inside our TS-code (as string literal)? Or maybe we should reconfigure our bundler to load CSS as string. But in this case it won't be minified.

And what should we do with server side rendering?

**Comment by rschristian** [comment]
I've done it before by having the bundler convert the entire CSS file into a string added to the JS bundle. It'll be minifed but there's no way to use something like purgecss on this and will increase bundle size. There might be some side issues with this, not totally sure. 

SSR will mean this needs to be treated like other browser JS which isn't great as this is CSS.

There's probably better ways out there, was just throwing in the single way I've done this before. I couldn't find anything better quickly enough so I resorted to doing that.

**Comment by rschristian** [comment]
Are there really that many projects that don't have a css-loader though? Every major CLI includes one by default as far as I am aware. 

Regardless I'd also love to get a solution here. I'm not overly happy with any of the CSS solutions I've come across, I feel that all have pretty significant drawbacks.

**Comment by molefrog** [comment]
I think the best way to figure this out is to ask real library users. What type of projects do they use react-colorful in (CRA/Next.js/custom)? How do they approach styling (CSS/PostCSS/CSS-in-JSS)? And most importantly: is this really a blocker for them to add an extra line of CSS import?

While I personally love the idea of a plug-n-play component that can only be required with a single line of code, when I look at this approach as a library user I see a couple of problems:
  - What if I need to run the app styles through a preprocessor like PostCSS?
  - What if don't want the library I see to have side effects such as inserting a `style` tag to the document? 

I would probably conduct an experiment by providing two entry points:
-  `react-colorful` — does have styles built-in 
- `react-colorful/pure` (?) not sure about the name, but brings no styles and allows to import css file separaetly.

**Comment by omgovich** [comment]
The biggest blocker is that many apps don't have a CSS-loader because they use CSS-in-JS and open-source components that are also based on CSS-in-JS.

Sometimes projects use a JS-compiler only (so it's impossible to add CSS-loader at all).
See [react-three-gui](https://github.com/birkir/react-three-gui) as an example.

I cloned a lot of repos to replace react-color with our library there. And I stuck on CSS-loading quite often.

**Comment by rschristian** [comment]
Well, certainly couldn't hurt to offer another option as CSS-in-JS.

**Comment by omgovich** [comment]
Thanks for your thoughts guys!
Will think about that
