### ISSUE TITLE
The color is not updated after dragging the handle to the corner

### ISSUE THREAD

**Issue by firede** [omgovich/react-colorful#73]
![CleanShot 2020-10-12 at 19 32 14](https://user-images.githubusercontent.com/157338/95742069-ff841600-0cc1-11eb-99b9-cec283d56de5.gif)

https://codesandbox.io/s/react-colorful-demo-u5vwp

**Comment by omgovich** [comment]
Hi, @firede. I can't catch the same behavior.

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/206567/95743207-09921e80-0c9a-11eb-94a4-ca2f49aa103e.gif)

Could you please describe your environment? I mean the browser name and version, OS.

**Comment by firede** [comment]
- macOS: 10.15.7
- Safari: 14.0 (15610.1.28.1.9, 15610)

**Comment by omgovich** [comment]
Looks like it's an old `currentColor` bug that was present in Safari 6–7.
Probably the developers of Safari missed this bug and decided to add it to Safari 14 again =)

**Comment by omgovich** [comment]
Hey, @firede. The problem is solved in v4.1.4 🤝
