### ISSUE TITLE
feat: expose ColorPickerBaseProps

### ISSUE THREAD

**Issue by atanasster** [omgovich/react-colorful#81]
Hi, thanks again for the great work.

Is it possible to export ColorPickerBaseProps, my use case is to create color pickers on the fly:

https://github.com/ccontrols/component-controls/blob/9f68190dbd39f50a3bb522646262410b8bd7e37e/ui/editors/src/ColorEditor/ColorEditor.tsx#L133

**Comment by omgovich** [comment]
Hmmm. 

It seems to me that we need out TS-ninja here =) @rschristian what do you think?

**Comment by atanasster** [comment]
I can submit a PR if you guys are ok with that proposal

**Comment by rschristian** [comment]
This seems like a quite odd use case and I'd argue against it. 

You can just use `typeof <colorpicker>` to get the types. There's really no reason for us to export that.

**Comment by atanasster** [comment]
@rschristian actually you are right, all the string color pickers have the same type. It will not work for other types like `HslaColorPicker` but I am closing this as it solves my issue

**Comment by rschristian** [comment]
So for the linked snippet, something like this:

```
let ColorPicker: typeof HexColorPicker | typeof RgbStringColorPicker | ...;
```

`ColorPickerBaseProps` is our internal method of more concisely and consistently declaring types. No real reason to export such a thing when the components themselves bring along the more correct type themselves (without the generic).

**Comment by omgovich** [comment]
Thanks, @rschristian!
You're the best! 👍

**Comment by kachkaev** [comment]
A quick solution for those who are here from search. I just bumped into an error after changing my tsconfg.

```
Cannot find module 'react-colorful/dist/types' or its corresponding type declarations.ts(2307)
```

Here is a diff that helped me:

```diff
-import type { ColorPickerBaseProps } from 'react-colorful/dist/types';
...
-const handleColorPickerChange: ColorPickerBaseProps<string>['onChange'] = (color) => {
+const handleColorPickerChange: Parameters<typeof HexColorPicker>[0]['onChange'] = (color) => {
```
