### ISSUE TITLE
css modules

### ISSUE THREAD

**Issue by atanasster** [omgovich/react-colorful#82]
Hi, 

I am not using the css style imports and this makes it hard to match the generated class names, as they are set up with css modules.

Here is my uses case, you will notice that I ended up using some strange selectors (`div[role=slider]` and a few other places) to accommodate that some class names are not possible without using css modules.

https://github.com/ccontrols/component-controls/blob/9f68190dbd39f50a3bb522646262410b8bd7e37e/ui/editors/src/ColorEditor/ColorEditor.tsx#L83

I would suggest to just hard-code the class names prefixed with 'react-colorful' so they stay fixed

**Comment by atanasster** [comment]
Just some more info on my issue, if it was not clear above:

Here is a div that didn't end up with a class name on my end: 
![grab106](https://user-images.githubusercontent.com/6075606/96754984-156b9800-13a0-11eb-8ca6-a1f6b6711fec.jpg)

Here is the same div from the official site: https://omgovich.github.io/react-colorful/ site (pointerFill class):
![grab107](https://user-images.githubusercontent.com/6075606/96755459-bfe3bb00-13a0-11eb-82b9-3e083faa939e.jpg)

You can play around with the class names without using css loaders on my end: https://component-controls.com/api/editors-coloreditor--overview

**Comment by omgovich** [comment]
Hi, @atanasster!

- you don't have CSS-loader configured
- you don't want to configure one since your package is 100% CSS-in-JS
- you don't provide CSS-file with your package

Right?

**Comment by omgovich** [comment]
I'm actually don't like that you have to copy our styled. 
We should find some way to import our stylesheet to your project.

We had a [discussion](https://github.com/omgovich/react-colorful/issues/72) about that with other maintainers, but haven't found a good solution yet.
But we'll try to help you somehow.

**Comment by omgovich** [comment]
@molefrog I probably need your advice here.

**Comment by atanasster** [comment]
Hi @omgovich ,

Yes I am 100% CSS-in-JS and do not have (or want to add) any css loaders. In this specific case I amusing theme-ui with emotion sx prop styling. 

I am not aware of any cross-style solution (that exports styles in css/e,otion/styled-components/etc.)

**Comment by omgovich** [comment]
In styled-components it's possible to import and apply a stylesheet like that:
```js
import pickerStyles from 'react-colorful/dist/index.css' // if CSS-loader is configured to load .css as strings

const Element = styled.div`
  ${pickerStyles};
`
```

As far as I understand you can't do the same with `theme-ui`, right?

**Comment by atanasster** [comment]
Thanks for pointing me to the discussion, I didnt see it when I was integrating react-colorful in my project. 

I am not aware of importing of raw css into emotion (and it would probably still need a css loader for the import). 
However I dont think this solution works for me, as it would still prevent from custom styling elements of react-colorful - as pointed above the elements either dont have a class name, or the class name is not stable and prone to change.

**Comment by atanasster** [comment]
Just my input, bt here is what I think would be an ok solution
- 'fix' the class names by removing the css modules 
- to prevent users from copy-pasting styles, possibly export an additional class of css-in-js styles (similar to what I have in my example). I am not aware of any third-part tool currently to automate it, but it could be a simple script that takes the js style class and creates a .css file or vice/versa.

**Comment by omgovich** [comment]
Just made an experimental PR that makes all class names static.
Suddenly, that makes the bundle size lighter by 1% =)

**Comment by atanasster** [comment]
Fantastic, thank you very much

**Comment by omgovich** [comment]
@atanasster Just deployed v4.4.0 with the static class names

**Comment by omgovich** [comment]
@molefrog @rschristian I have a proposal about CSS-in-JS version:

We create a separate package to keep the primary one dependency-free.

New package (let's call it `react-colorful-styled`) has two deps: `react-colorful` and `goober` (1 KB CSS-in-JS).

Inside the new package:
```js
import React from 'react';
import { HexColorPicker as Component } from 'react-colorful'
import { styled } from 'goober';
import stylesString from 'react-colorful' // rollup/webpack in this package will be configured to load CSS as a string

export const HexColorPicker = styled(Component)`
  ${stylesString}
`;
```

**Comment by omgovich** [comment]
We could probably improve project structure using workspaces (like React does in their repo)
```
/packages
  L react-colorful
    L src
  L react-colorful-styled
    L src
```

**Comment by rschristian** [comment]
Hmm, I'd toss in for a `react-coloful/styled` and more of the Preact approach personally. To me anyways it looks a bit simpler. [Link for reference repo](https://github.com/preactjs/preact). Looks a bit like this:

```
package.json (core)
src/
---(core)
styled/
----package.json
----src/ 
```

I wonder, have you checked to see if Microbundle will read a CSS import as a string? I know it can inline a JSON file as a string no-problem, so I'm curious to see what would happen if we try to import a CSS file as a string in TS while disabling CSS modules. I'll give that a shot. 

`goober` and TS might be interesting though. I mean worse comes to worst, we'll have to maybe write a generic for it and do a few `typeof HexColorPicker` or whatever, so it shouldn't be too bad. I've only used Goober over an afternoon though, so not entirely sure how well it handles TS.

**Comment by omgovich** [comment]
> Hmm, I'd toss in for a react-colorful/styled and more of the Preact approach personally.

The problem with importing something from `react-colorful/styled` is that our package needs to have `goober` in dependencies then.

**Comment by rschristian** [comment]
I don't believe so? Not with export maps.

**Comment by omgovich** [comment]
As far as I know that's how NPM/Yarn works.
When you run `npm install react-colorful` it installs `react-colorful` and all packages defined in `react-colorful/package.json`. It doesn't parse other package.json files that package might contain.

**Comment by rschristian** [comment]
Whoops, alright, yeah, avoid that then.

**Comment by rschristian** [comment]
So it looks like Microbundle can read a CSS file to an inlined string for us so that'll simplify things

**Comment by omgovich** [comment]
Could you show how? It would help me a lot

**Comment by atanasster** [comment]
any solution you can think of that would not add a goober dependency? Also maybe not call it react-colorful/styled as it can be confusing that it is using styled-components.

**Comment by rschristian** [comment]
> Could you show how? It would help me a lot

Hm, actually, works for everything but cjs. I'll see if that's easy to fix. 

But it's just a matter of disabling css-modules and then importing the CSS like `import styles from 'x.css';`

> any solution you can think of that would not add a goober dependency? Also maybe not call it react-colorful/styled as it can be confusing that it is using styled-components.

Well we'd need to add *a* dependency. Writing our own CSS-in-JS lib would be expensive to write and maintain.

**Comment by omgovich** [comment]
Hmm, actually we could go back to our idea about adding a `<style>` to `<head>`.
Drawback: that's a side effect. But our styles are just 600 bytes, for I think not a big deal.

**Comment by atanasster** [comment]
> Well we'd need to add a dependency. Writing our own CSS-in-JS lib would be expensive to write and maintain.

Sorry - I meant the following 
 - the lib does not use by default any css/js etc styling, leaving it to the end-user to select what to use.
- export a `.css` file, and users with css-loader will import it ss it is currently required in the documentation
- export a css-in-js `.js` file with  the styling object and users that use (already have an emotion dependency for example) can import this styling instead of the css file.

**Comment by omgovich** [comment]
That's pretty hard to convert our styled to JS-object. Don't think that it's a good way for us in terms of maintenance.

**Comment by omgovich** [comment]
> Hmm, actually we could go back to our idea about adding a <style> to <head>.

Them our API will look like this:
```js
import { HecColorPicker} from 'react-colorful/css-in-js'
import 'react-colorful/css-in-js'
```

Source of the `css-in-js`
```js
import stylesString from 'react-colorful/dist/index.css'

const styleElement = document.createElement('style');
styleElement.textContent = stylesString;
document.body.appendChild(styleElement);
```

**Comment by rschristian** [comment]
> > Hmm, actually we could go back to our idea about adding a <style> to .
> 
> Then our API will look like this:
> 
> ```js
> import { HecColorPicker} from 'react-colorful/css-in-js'
> import 'react-colorful/css-in-js'
> ```
> 
> Source of the `css-in-js`
> 
> ```js
> import stylesString from 'react-colorful/dist/index.css'
> 
> // probably require some check to avoid crushing on SSR
> const styleElement = document.createElement('style');
> styleElement.textContent = stylesString;
> document.body.appendChild(styleElement);
> ```

Correct me if I'm wrong, but wouldn't calling this CSS-in-JS be quite wrong? It's just loading a CSS stylesheet and avoiding the style-loader. It's not true CSS-in-JS, there's no way to restyle without manually targeting the classes. 

If that's what CSS-in-JS user's expect then that's fine, I'm just not one of them so I'm not sure.

**Comment by omgovich** [comment]
Yeah. This name is sucks, agree. Probably should call it `react-colorful/inject-styled` or something)

**Comment by omgovich** [comment]
This idea is good because allows us to keep a simple project structure and avoid dependencies at all.

**Comment by rschristian** [comment]
Yeah, I think that's more true to what it does. I'm going to play around with Microbundle some more, might just contact Jason to see if he knows what's going on here. All of our exports can stringify the CSS inline except `index.js`.

**Comment by omgovich** [comment]
Thanks, Ryan!

**Comment by omgovich** [comment]
I guess the most difficult part is the bundler configuration. As far as I see, we need two different build-steps:
1. Build the JS and CSS to /dist, minify styles.
2. Build `inject-styles`js-code and load minified styled from dist as a string.

**Comment by rschristian** [comment]
Bundler config should be pretty easy actually. Microbundle will automatically minimize the string CSS even from raw. 

I think this is just a matter of running another instance of Microbundle (like we used to)

**Comment by atanasster** [comment]
@omgovich 

- the static class names work great, that a lot.

- I am afraid the css-in-js style as string might not work for my use case - for dark theme, as well as theme colors I do need to customize some of the style props. Here is an example using the theme's shadow color: https://github.com/ccontrols/component-controls/blob/3979cc661416b91921cc462dac48bd35979e3a49/ui/editors/src/ColorEditor/ColorEditor.tsx#L48
If the styling is provided as an object, I could re-use the rest of the style props and just override the styles that are theme-dependent. I any case I don't think its a huge issue - probably the styles are not going to change much and the main issue was the static class names that is now solved.

- I created a small documentation site for react-colorful with component-controls https://react-colorful.netlify.app (it also has jest snapshot tests on all stories as a bonus - yarn test-docs). 
I will submit a PR if you like it, here is the code: https://github.com/atanasster/react-colorful/tree/component-controls .

**Comment by omgovich** [comment]
Hi @atanasster. We're working on a solution that will inject the default styles to the `<head>`, so won't need to copy all our styles. You will just customize override specific elements' styles. Let's just wait for news from @rschristian)

Regarding the docs. Thanks for your site, look good! But I'm considering to launch something more promotional. The library API itself is pretty simple, so we don't need big documentation. We're going to extend our current website to create something like https://iro.js.org, but even more interactive, beautiful, and promotional.

**Comment by omgovich** [comment]
Discussion moved to #87
