### ISSUE TITLE
Component looks empty (but it's not)

### ISSUE THREAD

**Issue by rafalbromirski** [omgovich/react-colorful#85]
Hey,

Today I wanted to upgrade my package and after doing it I've noticed empty space instead of a color picker component.

Everything renders correctly (I see DOM nodes but it's just blank)

It seems like it's also visible in your examples: https://codesandbox.io/s/react-colorful-customization-demo-mq85z?file=/src/index.js

### Preview:

![image](https://user-images.githubusercontent.com/130297/97021305-f4977400-1552-11eb-8fd1-0f1b510107b5.png)
![image](https://user-images.githubusercontent.com/130297/97021590-4fc96680-1553-11eb-989e-cacde2a66690.png)

Other details:
- system: OSX 10.15.6
- browser: Chrome 85.0.4183.121

Cheers,
R

**Comment by rafalbromirski** [comment]
UPDATE: Seems like css is wrong. It doesn't have correct classes:

```css
._2UwNG { ... }
```

**Comment by omgovich** [comment]
Hi @rafalbromirski. We recently removed CSS-modules and replaced them with static class names, probably our bundler minified the class names. Gonna check how can we prevent class name minification.

**Comment by omgovich** [comment]
Thanks for your issue. Don't know how could I missed that.

**Comment by omgovich** [comment]
Just deployed `v4.4.1`.
